import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
const projectID = process.env.PERSISTTY_E2E_W06_PROJECT, root = process.env.PERSISTTY_E2E_W06_ROOT;
test("W06 本机真实搜索定位、冲突与应用、Git 比较和移动视图", async ({ page, context, browserName }, testInfo) => {
  test.skip(!projectID || !root?.startsWith("/private/tmp/persistty-w06-browser-"), "仅操作本轮显式隔离 fixture");
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  const hash = (value: Buffer) => createHash("sha256").update(value).digest("hex");
  const originalIndex = hash(await readFile(`${root}/.git/index`)), originalHEAD = hash(await readFile(`${root}/.git/HEAD`));
  if (browserName === "chromium") await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.goto(`/projects/${projectID}`); await page.getByLabel("访问密码").fill(process.env.PERSISTTY_E2E_PASSWORD!); await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("heading", { name: "W06 本地开发检查" })).toBeVisible();
  const session = (await (await page.request.get("/api/v1/auth/session")).json()).data;
  const project = (await (await page.request.get(`/api/v1/projects/${projectID}`)).json()).data;
  const endpoint = `/api/v1/projects/${projectID}/folders/${project.main_folder_id}/content`, headers = { Origin: process.env.PERSISTTY_E2E_BASE_URL!, "X-CSRF-Token": session.csrf_token };
  const initial = (await (await page.request.get(`${endpoint}?project_version=1&path=sample.txt`)).json()).data;
  if (initial.content !== "😀hit\nsecond hit\n") expect((await page.request.put(endpoint, { headers, data: { project_version: 1, path: "sample.txt", expected_version: initial.version, content: "😀hit\nsecond hit\n" } })).ok()).toBe(true);
  await page.keyboard.press("ControlOrMeta+Shift+f"); await expect(page.getByLabel("搜索内容")).toBeFocused(); await page.getByLabel("搜索内容").fill("hit"); await page.getByRole("button", { name: "搜索范围与文件过滤", exact: true }).click(); await page.getByLabel("包含文件").fill("sample.txt;ignored.txt"); await page.getByRole("button", { name: "搜索", exact: true }).click();
  await expect(page.getByText("1 个文件 · 2 处匹配 · 0 项跳过", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: /^1:3/ }).click(); await expect(page.locator(".monaco-editor").first()).toBeVisible();
  if (browserName === "chromium") { await page.keyboard.press("ControlOrMeta+c"); await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe("hit"); }
  else await expect(page.locator(".monaco-editor .selected-text").first()).toBeVisible();
  await page.getByLabel("替换为").fill("done"); await page.getByRole("button", { name: /预览选中项替换/ }).click();
  const dialog = page.getByRole("dialog"); await expect(dialog).toBeVisible(); await expect(dialog.getByRole("button", { name: "关闭预览", exact: true })).toBeFocused(); await dialog.getByRole("button", { name: "sample.txt · 2 处", exact: true }).click(); await expect(dialog.locator(".monaco-diff-editor")).toBeVisible();
  const snapshot = (await (await page.request.get(`${endpoint}?project_version=1&path=sample.txt`)).json()).data;
  expect((await page.request.put(endpoint, { headers, data: { project_version: 1, path: "sample.txt", expected_version: snapshot.version, content: "😀hit\nexternal hit\n" } })).ok()).toBe(true);
  await dialog.getByRole("button", { name: "确认应用到 1 个文件", exact: true }).click(); await expect(dialog.getByText(/版本冲突，未替换|已跳过/)).toBeVisible();
  expect((await (await page.request.get(`${endpoint}?project_version=1&path=sample.txt`)).json()).data.content).toBe("😀hit\nexternal hit\n");
  await dialog.getByRole("button", { name: "关闭预览", exact: true }).click(); await page.getByRole("button", { name: "搜索", exact: true }).click();
  await expect(page.getByRole("button", { name: /预览选中项替换/ })).toBeEnabled(); await page.getByRole("button", { name: /预览选中项替换/ }).click(); await dialog.getByRole("button", { name: "确认应用到 1 个文件", exact: true }).click(); await expect(dialog.getByText("已替换", { exact: true })).toBeVisible();
  expect((await (await page.request.get(`${endpoint}?project_version=1&path=sample.txt`)).json()).data.content).toBe("😀done\nexternal done\n");
  await dialog.getByRole("button", { name: "读取应用状态", exact: true }).click(); await expect(dialog.getByText("已替换", { exact: true })).toBeVisible(); await dialog.getByRole("button", { name: "关闭预览", exact: true }).click();
  await expect(page.locator(".git-line-modified").first()).toBeVisible();
  await page.getByRole("button", { name: "只读 Git", exact: true }).click(); await expect(page.getByRole("region", { name: "只读 Git" })).toBeVisible(); await page.getByRole("button", { name: /^sample.txt/ }).click(); await expect(dialog.locator(".monaco-diff-editor")).toBeVisible(); await dialog.getByRole("checkbox", { name: "比较当前编辑器输入（打开比较时的快照）" }).check(); await dialog.getByRole("button", { name: "关闭比较", exact: true }).click();
  await page.getByRole("button", { name: /^initial/ }).click(); await expect(page.locator(".git-commit-detail").getByRole("button", { name: "sample.txt", exact: true })).toBeVisible(); await page.locator(".git-commit-detail").getByRole("button", { name: "sample.txt", exact: true }).click(); await expect(dialog).toBeVisible(); await dialog.getByRole("button", { name: "关闭比较", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole("button", { name: "Git", exact: true }).click(); await expect(page.getByRole("region", { name: "只读 Git" })).toBeVisible(); await page.getByRole("region", { name: "变更内容" }).getByRole("button", { name: /^sample.txt/ }).click(); await expect(dialog.getByRole("region", { name: "原内容" })).toBeVisible(); await expect(dialog.getByRole("region", { name: "比较内容" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("mobile-git.png") }); await dialog.getByRole("button", { name: "关闭比较", exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); expect(hash(await readFile(`${root}/.git/index`))).toBe(originalIndex); expect(hash(await readFile(`${root}/.git/HEAD`))).toBe(originalHEAD); expect(errors).toEqual([]);
});
test("W06 替换传输等待时可明确停止剩余项，取消零写入", async ({ page }) => {
  test.skip(!projectID || !root?.startsWith("/private/tmp/persistty-w06-browser-"), "仅操作本轮显式隔离 fixture");
  await page.goto(`/projects/${projectID}`); await page.getByLabel("访问密码").fill(process.env.PERSISTTY_E2E_PASSWORD!); await page.getByRole("button", { name: "登录", exact: true }).click(); await expect(page.getByRole("heading", { name: "W06 本地开发检查" })).toBeVisible();
  const before = await readFile(`${root}/sample.txt`);
  await page.getByRole("button", { name: "搜索与替换", exact: true }).click(); await page.getByLabel("搜索内容").fill(before.toString().includes("done") ? "done" : "hit"); await page.getByRole("button", { name: "搜索", exact: true }).click(); await page.getByLabel("替换为").fill("never written"); await page.getByRole("button", { name: /预览选中项替换/ }).click();
  let release: () => void = () => {}; const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route("**/replace-previews/*/apply", async route => { await gate; await route.abort().catch(() => {}); });
  const dialog = page.getByRole("dialog"); await dialog.getByRole("button", { name: "确认应用到 1 个文件", exact: true }).click(); await dialog.getByRole("button", { name: "停止剩余替换", exact: true }).click();
  await expect(dialog.getByText("预览已取消，未提交的文件不会写入。", { exact: true })).toBeVisible(); release(); expect(await readFile(`${root}/sample.txt`)).toEqual(before);
});
